# This file was automatically generated by SWIG
package mp3dec;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package mp3dec;
bootstrap mp3dec;
var_mp3dec_init();
package mp3dec;
@EXPORT = qw( );
1;
