.TH "TOC2CDDB" "1" "2006-11-17" "1.2.2" "CDRDAO"

.SH "NAME"
toc2cddb \- translates a TOC file of
.I cdrdao(1)
into a cddb file and prints it to stdout

.SH "SYNOPSIS"
.B toc2cddb
.I toc_file
.PP
.B toc2cddb
.BR [\| \-h \||\| \-V \|]

.SH "DESCRIPTION"
.B toc2cddb
translates a TOC file of
.I cdrdao(1)
into a cddb file and prints it to stdout.

.SH "OPTIONS"
.TP
.B \-h
Shows a short help message.
.TP
.B \-V
Prints the version of toc2cddb.

.SH "SEE ALSO"
.I cdrdao(1)

.SH "AUTHOR"
.B toc2cddb
was written by Giuseppe "Cowo" Corbelli <cowo@lugbs.linux.it> and is part of
.I cdrdao(1)
written by Andreas Mueller <andreas@daneb.de>.
.PP
This manual page was written by Francois Wendling <frwendling@free.fr> and revised by Daniel Baumann <daniel@debian.org>, for the Debian project (but may be used by others).
