#!/bin/sh
###########################################################################
#ident "@(#)MKLINKS	1.24 99/07/27 "
###########################################################################
# Written 1996 by J. Schilling
###########################################################################
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
###########################################################################
ln -s	mk-.id			mk-make.id
ln -s	r-make.c4x		r-gmake.c4x
ln -s	r-make.c4x-dep		r-gmake.c4x-dep
ln -s	r-make.obj		r-gmake.obj
ln -s	9000-725-hp-ux-cc.rul	9000-710-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-712-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-715-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-735-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-743-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-780-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-782-hp-ux-cc.rul
ln -s	9000-725-hp-ux-cc.rul	9000-755-hp-ux-cc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-710-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-712-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-715-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-735-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-743-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-755-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-780-hp-ux-gcc.rul
ln -s	9000-725-hp-ux-gcc.rul	9000-782-hp-ux-gcc.rul
ln -s	hppa-nextstep-cc.rul	i386-nextstep-cc.rul
ln -s	hppa-nextstep-cc.rul	m68k-nextstep-cc.rul
ln -s	hppa-nextstep-cc.rul	sparc-nextstep-cc.rul
ln -s	hppa-nextstep-cc.rul	i386-nextstep-gcc.rul
ln -s	hppa-nextstep-cc.rul	m68k-nextstep-gcc.rul
ln -s	hppa-nextstep-cc.rul	sparc-nextstep-gcc.rul
ln -s	os-irix.id		os-irix64.id
ln -s	ip22-irix-cc.rul	ip20-irix-cc.rul
ln -s	ip22-irix-cc.rul	ip28-irix-cc.rul
ln -s	ip22-irix-cc.rul	ip30-irix-cc.rul
ln -s	ip22-irix-cc.rul	ip32-irix-cc.rul
ln -s	i386-netbsd-cc.rul	sparc-netbsd-cc.rul
ln -s	i386-netbsd-gcc.rul	sparc-netbsd-gcc.rul
ln -s	i386-netbsd-cc.rul	mac68k-netbsd-cc.rul
ln -s	i386-netbsd-gcc.rul	mac68k-netbsd-gcc.rul
ln -s	i386-bsd-os-gcc.rul	sparc-bsd-os-gcc.rul
ln -s	i586-linux-cc.rul	i386-linux-cc.rul
ln -s	i586-linux-cc.rul	i486-linux-cc.rul
ln -s	i586-linux-cc.rul	i686-linux-cc.rul
ln -s	i586-linux-gcc.rul	i386-linux-gcc.rul
ln -s	i586-linux-gcc.rul	i486-linux-gcc.rul
ln -s	i586-linux-gcc.rul	i686-linux-gcc.rul
ln -s	i586-linux-cc.rul	sparc-linux-cc.rul
ln -s	i586-linux-gcc.rul	sparc-linux-gcc.rul
ln -s	i586-linux-cc.rul	sparc64-linux-cc.rul
ln -s	i586-linux-gcc.rul	sparc64-linux-gcc.rul
ln -s	i586-linux-cc.rul	alpha-linux-cc.rul
ln -s	i586-linux-gcc.rul	alpha-linux-gcc.rul
ln -s	i586-linux-cc.rul	ppc-linux-cc.rul
ln -s	i586-linux-gcc.rul	ppc-linux-gcc.rul
ln -s	i586-linux-cc.rul	m68k-linux-cc.rul
ln -s	i586-linux-gcc.rul	m68k-linux-gcc.rul
ln -s	i586-linux-cc.rul	armv4l-linux-cc.rul
ln -s	i586-linux-gcc.rul	armv4l-linux-gcc.rul
ln -s	os-cygwin32_nt.id	os-cygwin_nt-4.0.id
ln -s	os-cygwin32_nt.id	os-cygwin_95-4.0.id
ln -s	os-cygwin32_nt.id	os-cygwin_98-4.0.id
ln -s	i486-cygwin32_nt-cc.rul	i586-cygwin32_nt-cc.rul
ln -s	i486-cygwin32_nt-cc.rul	i686-cygwin32_nt-cc.rul
ln -s	i486-cygwin32_nt-gcc.rul	i586-cygwin32_nt-gcc.rul
ln -s	i486-cygwin32_nt-gcc.rul	i686-cygwin32_nt-gcc.rul
ln -s	sun4-sunos4-cc.rul	sun4c-sunos4-cc.rul
ln -s	sun4-sunos4-gcc.rul	sun4c-sunos4-gcc.rul
ln -s	sun4-sunos5-cc.rul	sun4c-sunos5-cc.rul
ln -s	sun4-sunos5-gcc.rul	sun4c-sunos5-gcc.rul
ln -s	sun4-sunos4-cc.rul	sun4m-sunos4-cc.rul
ln -s	sun4-sunos4-gcc.rul	sun4m-sunos4-gcc.rul
ln -s	sun4-sunos5-cc.rul	sun4m-sunos5-cc.rul
ln -s	sun4-sunos5-gcc.rul	sun4m-sunos5-gcc.rul
ln -s	sun4-sunos5-cc.rul	sun4u-sunos5-cc.rul
ln -s	sun4-sunos5-gcc.rul	sun4u-sunos5-gcc.rul
ln -s	sun4-sunos5-cc.rul	sun4d-sunos5-cc.rul
ln -s	sun4-sunos5-gcc.rul	sun4d-sunos5-gcc.rul
ln -s	sun4-sunos5-cc.rul	sun4e-sunos5-cc.rul
ln -s	sun4-sunos5-gcc.rul	sun4e-sunos5-gcc.rul
ln -s	sun4-sunos5-cc.rul	sun4L-sunos5-cc.rul
ln -s	sun4-sunos5-gcc.rul	sun4L-sunos5-gcc.rul
#
ln -s	mk-smake.id		mk-build.id
ln -s	r-smake.c4x		r-build.c4x
ln -s	r-smake.c4x-dep		r-build.c4x-dep
ln -s	r-smake.dep		r-build.dep
ln -s	r-smake.obj		r-build.obj
ln -s	r-smake.tag		r-build.tag
