#ident "%W% %E% %Q%"
###########################################################################
SRCROOT=	..
RULESDIR=	RULES
include		$(SRCROOT)/$(RULESDIR)/rules.top
###########################################################################

#MK_FILES= libschily.mk libschily_p.mk shlschily.mk
MK_FILES= libschily.mk

###########################################################################
include		$(SRCROOT)/$(RULESDIR)/rules.mks
###########################################################################
