#!/bin/sh

#./RULES/os-sunos.id
#./RULES/os-sunos.def
#./DEFAULTS/Defaults.sunos
#./RULES/sun4c-sunos-gcc.rul

	case $1 in

	*os-*.id)
		echo $1
		echo > $1
		;;
	
	*os-*.def)
		echo $1
		echo > $1
		;;
	
	*Defaults.*)
		echo $1
		echo > $1
		;;
	
	*-*-*cc.rul)
		echo $1
		echo > $1
		;;

	*)
		echo "Unknown rule to build: '$1'."
		exit 1
		;;
	
	esac
