#!/bin/sh
#
# Replacement for mkdir -p ... functionality.
#
# BSD-4.3, NeXT Step <= 3.x and similar don't accept the -p flag
#
# @(#)mkdir-sh	1.2 98/12/14 Copyright 1998 J. Schilling
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.  If not, write to
# the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.

if [ $# -lt 1 ]; then
	echo "Usage: mkdir-sh [-p] dir ...."
	exit 1
fi

dop=false
case $1 in
-p)
	dop=true
	shift
	;;
esac

if [ $dop = false ]; then
	for i in "$@"; do
		mkdir "$i"
	done
else
	for i in "$@"; do
		if [ -d "$i" ]; then
			continue
		fi
		# Don't use ${i:-.}, BSD4.3 doen't like it
		#
		fullname="$i"
		if [ ."$i" = . ]; then
			fullname=.
		fi
		dirname=`expr \
			"$fullname/" : '\(/\)/*[^/]*//*$'  \| \
			"$fullname/" : '\(.*[^/]\)//*[^/][^/]*//*$' \| \
			.`
		sh $0 -p "$dirname"
		mkdir "$i"
	done
fi
